server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/familie_munshi_db
    username: postgres
    password: 9016
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

minio:
  url: http://localhost:9000
  access-key: minioadmin
  secret-key: minioadmin
  bucket-name: familiemunshi-bucket

logging:
  level:
    root: INFO
    com.familiemunshi: DEBUG