server:
  port: ${PORT:8080}

spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: false

minio:
  url: ${MINIO_URL:http://minio:9000}
  access-key: ${MINIO_ACCESS_KEY:${MINIO_ROOT_USER}}
  secret-key: ${MINIO_SECRET_KEY:${MINIO_ROOT_PASSWORD}}
  bucket-name: ${MINIO_BUCKET_NAME:familiemunshi-bucket}